//! Engine B — Concurrency & Saturation Curve Sweeper (plan Chunk 10,
//! blueprint §5 Engine B).
//!
//! A [`Sweep`] steps a configurable concurrency ladder (default
//! `1→2→4→8→16→32→64` simultaneous sessions), running a fixed workload
//! (one prompt, `max_tokens`) at `n` concurrent [`WorkerPool`] streams per
//! level, and collects per level:
//!
//! * **aggregate tokens/sec** — total tokens generated across *all* streams
//!   of the level divided by the level's wall time (blueprint: "System
//!   Generation Throughput (Aggregate Tokens/Sec across all streams)");
//! * **client-perceived p90 TPOT** — the 90th percentile of inter-token
//!   latencies pooled across *all* streams of the level (blueprint:
//!   "Client-Perceived Latency (p90 TPOT)");
//! * TTFT percentiles (one sample per stream), per-stream detail rows
//!   ([`StreamMetric`]), and completion/failure counts.
//!
//! The resulting [`SweepResult`] feeds the saturation knee-point detection
//! ([`SweepResult::detect_knee`] — the level where aggregate throughput
//! plateaus while p90 TPOT spikes, i.e. the memory-bandwidth-bound →
//! compute-bound transition) and the "Optimal Operational Envelope"
//! ([`SweepResult::envelope`] — the recommended sweet spot), and is the
//! data View 2 (Concurrency Matrix) renders with the knee highlighted.
//!
//! **Measurement isolation** (blueprint §4): all timing comes from the
//! workers' `quanta` stamps — the sweep only *consumes* tagged events. The
//! optional [`MetricsState`] publisher (the TUI seam) reads the same events
//! the sweep consumes and publishes in batches, so the render loop never
//! touches the timing path.

use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use crate::client::pool::{PoolEvent, WorkerPool};
use crate::client::StreamError;
use crate::engines::sequence::{EngineProgress, ProgressBus, RunPause};
use crate::log::{Context, RunLogger};
use crate::metrics::histogram::LatencyHistogram;
use crate::metrics::state::{MetricsSnapshot, MetricsState, StreamMetric, StreamStatus};
use crate::sse::{Chunk, Usage};
use crate::timing::MonotonicInstant;

/// The default concurrency ladder (blueprint §5 Engine B:
/// `1→2→4→8→16→32→64` simultaneous sessions).
pub const DEFAULT_LADDER: [usize; 7] = [1, 2, 4, 8, 16, 32, 64];

/// The stall-detection window for the *inter-token* phase: a worker that
/// has received at least one token and then goes silent for this long is
/// flagged (warned) as stalled. The per-worker timeout (the pool's
/// `worker_timeout`) is what eventually kills it.
pub const DEFAULT_STALL_TIMEOUT: Duration = Duration::from_secs(30);

/// The stall-detection floor for the *TTFB* phase (no token received
/// yet): at high concurrency the server batch-schedules, so a worker
/// waiting in the queue is *not* stalled — it gets this longer leash
/// (or the pool's per-worker timeout / 2, when that is larger) before a
/// warning fires.
pub const DEFAULT_TTFB_STALL_TIMEOUT: Duration = Duration::from_secs(90);

/// The cadence of the sweep's stall / step-budget checks (the drain
/// loop wakes on this interval between events).
const STALL_CHECK_INTERVAL: Duration = Duration::from_secs(5);

/// Normalize a user-supplied ladder: drop non-positive entries, remove
/// duplicates, sort ascending.
pub fn normalize_ladder(ladder: impl IntoIterator<Item = usize>) -> Vec<usize> {
    let mut v: Vec<usize> = ladder.into_iter().filter(|&n| n > 0).collect();
    v.sort_unstable();
    v.dedup();
    v
}

/// One ladder step of a [`Sweep`]: a point on the throughput/latency curve.
#[derive(Debug, Clone)]
pub struct SweepLevel {
    /// The concurrency of this step.
    pub concurrency: usize,
    /// System Generation Throughput: aggregate tokens/sec across all
    /// streams of the level.
    pub aggregate_tps: f64,
    /// Inter-token latency percentiles (ns), pooled across all streams.
    pub p50_tpot_ns: u64,
    pub p90_tpot_ns: u64,
    pub p99_tpot_ns: u64,
    /// TTFT percentiles (ns) — one sample per stream.
    pub ttft_p50_ns: u64,
    pub ttft_p90_ns: u64,
    /// Total tokens generated by every stream in the level.
    pub total_tokens: u64,
    /// Streams that completed (clean `[DONE]` or premature close).
    pub completed_streams: usize,
    /// Streams that failed (HTTP / connection / timeout / read error).
    pub failed_streams: usize,
    /// Workers killed by the per-worker timeout (the freeze fix). Their
    /// partial tokens are included in `total_tokens`.
    pub timed_out_streams: usize,
    /// `true` when the step-level timeout aborted the level (the sweep
    /// collected whatever it had and moved on to the next step).
    pub aborted: bool,
    /// Wall time of the level (spawn → last worker finished), in ns.
    pub wall_ns: u64,
    /// Per-stream detail (View 1 stream-matrix rows; blueprint §8
    /// `stream_metrics`).
    pub streams: Vec<StreamMetric>,
}

impl SweepLevel {
    /// p50 TPOT in milliseconds (for display).
    pub fn p50_tpot_ms(&self) -> f64 {
        self.p50_tpot_ns as f64 / 1_000_000.0
    }

    /// p90 TPOT in milliseconds (for display).
    pub fn p90_tpot_ms(&self) -> f64 {
        self.p90_tpot_ns as f64 / 1_000_000.0
    }

    /// p99 TPOT in milliseconds (for display).
    pub fn p99_tpot_ms(&self) -> f64 {
        self.p99_tpot_ns as f64 / 1_000_000.0
    }

    /// p50 TTFT in milliseconds.
    pub fn ttft_p50_ms(&self) -> f64 {
        self.ttft_p50_ns as f64 / 1_000_000.0
    }

    /// p90 TTFT in milliseconds.
    pub fn ttft_p90_ms(&self) -> f64 {
        self.ttft_p90_ns as f64 / 1_000_000.0
    }

    /// Level wall time in seconds.
    pub fn wall_secs(&self) -> f64 {
        self.wall_ns as f64 / 1_000_000_000.0
    }

    /// `true` when the level ran degraded: at least one worker was
    /// killed by the per-worker timeout, or the step was aborted by the
    /// step-level timeout. Its curve point is still usable (partial
    /// results were collected), but it should be treated with care in
    /// knee detection / the envelope.
    pub fn degraded(&self) -> bool {
        self.timed_out_streams > 0 || self.aborted
    }
}

/// The full sweep curve: one [`SweepLevel`] per ladder step.
#[derive(Debug, Clone, Default)]
pub struct SweepResult {
    pub levels: Vec<SweepLevel>,
}

impl SweepResult {
    /// `true` when no level ran.
    pub fn is_empty(&self) -> bool {
        self.levels.is_empty()
    }

    /// The level with the highest aggregate throughput — the fallback
    /// sweet spot when [`Self::detect_knee`] finds no saturation
    /// transition on the curve.
    pub fn peak_throughput(&self) -> Option<&SweepLevel> {
        self.levels
            .iter()
            .max_by(|a, b| a.aggregate_tps.total_cmp(&b.aggregate_tps))
    }

    /// Detect the saturation knee (blueprint §5 Engine B "Throughput
    /// Knee-Point Detection", plan Chunk 11).
    ///
    /// The knee is the *first* level (ascending concurrency) at which
    /// **both** hold relative to the previous level:
    ///
    /// 1. the aggregate-throughput gain drops to
    ///    [`KNEE_GAIN_THRESHOLD`] or below — throughput has plateaued;
    /// 2. the p90 TPOT grows by at least [`KNEE_SPIKE_THRESHOLD`]× —
    ///    client latency is spiking.
    ///
    /// That dual condition is the memory-bandwidth-bound (under-saturated)
    /// → compute-bound (saturated) transition. Returns [`None`] when the
    /// curve shows no such transition (fewer than two levels, throughput
    /// still climbing, or latency never spikes) — the envelope then falls
    /// back to [`Self::peak_throughput`].
    ///
    /// Pure function over the curve: no timing, no locks (measurement
    /// isolation, blueprint §4).
    pub fn detect_knee(&self) -> Option<KneePoint> {
        let mut levels: Vec<&SweepLevel> = self.levels.iter().collect();
        levels.sort_by_key(|l| l.concurrency);
        for (prev, cur) in levels.windows(2).map(|w| (w[0], w[1])) {
            let gain = relative_gain(prev.aggregate_tps, cur.aggregate_tps);
            let spike = relative_spike(prev.p90_tpot_ns, cur.p90_tpot_ns);
            if gain <= KNEE_GAIN_THRESHOLD && spike >= KNEE_SPIKE_THRESHOLD {
                return Some(KneePoint {
                    concurrency: cur.concurrency,
                    sweet_spot: prev.concurrency,
                    aggregate_tps: cur.aggregate_tps,
                    p90_tpot_ns: cur.p90_tpot_ns,
                });
            }
        }
        None
    }

    /// The "Optimal Operational Envelope" (blueprint §6 View 2): the
    /// recommended sweet spot for hosting this model on the target
    /// hardware — the level just before the detected knee, or the
    /// peak-throughput level when the curve is healthy (no knee).
    pub fn envelope(&self) -> Option<Envelope> {
        let knee = self.detect_knee();
        let sweet = match knee {
            Some(k) => k.sweet_spot,
            None => self.peak_throughput()?.concurrency,
        };
        let level = self.levels.iter().find(|l| l.concurrency == sweet)?;
        Some(Envelope {
            sweet_spot: level.concurrency,
            aggregate_tps: level.aggregate_tps,
            p90_tpot_ns: level.p90_tpot_ns,
            knee,
        })
    }
}

/// Relative aggregate-throughput gain at or below which a level is
/// considered to have *plateaued* (the knee's throughput condition).
pub const KNEE_GAIN_THRESHOLD: f64 = 0.05;

/// p90-TPOT growth factor (vs the previous level) at or above which a
/// level is considered to be *spiking* (the knee's latency condition).
pub const KNEE_SPIKE_THRESHOLD: f64 = 2.0;

/// The detected saturation knee: the first concurrency level where
/// aggregate throughput plateaus while p90 TPOT spikes (blueprint §5
/// Engine B — the memory-bandwidth-bound → compute-bound transition).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct KneePoint {
    /// The concurrency at the knee (the first saturated level).
    pub concurrency: usize,
    /// The recommended sweet spot: the last level before the knee.
    pub sweet_spot: usize,
    /// Aggregate throughput (t/s) at the knee.
    pub aggregate_tps: f64,
    /// p90 TPOT (ns) at the knee — the spiking side.
    pub p90_tpot_ns: u64,
}

/// The "Optimal Operational Envelope" (blueprint §6 View 2): the
/// recommended sweet spot, with the detected knee (when the curve shows a
/// saturation transition) attached.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Envelope {
    /// The recommended concurrency (the sweet spot).
    pub sweet_spot: usize,
    /// Aggregate throughput (t/s) at the sweet spot.
    pub aggregate_tps: f64,
    /// p90 TPOT (ns) at the sweet spot.
    pub p90_tpot_ns: u64,
    /// The detected knee, if the curve showed a saturation transition.
    pub knee: Option<KneePoint>,
}

/// A concurrency ladder sweep (blueprint §5 Engine B).
///
/// One [`WorkerPool`] (shared connection-pooled client) is stepped through
/// the ladder level by level; each level runs to completion before the
/// next starts, so every curve point measures a steady population of
/// `n` concurrent streams.
#[derive(Clone)]
pub struct Sweep {
    pool: WorkerPool,
    ladder: Vec<usize>,
    /// Optional TUI seam: publish live [`MetricsSnapshot`]s while the sweep
    /// runs (the render loop reads them lock-free).
    metrics: Option<Arc<MetricsState>>,
    /// Optional sequence seam: publish `Concurrency level … (step …)` +
    /// streams active to the [`ProgressBus`] the Benchmark Sequence
    /// mirrors into the TUI's progress bar.
    progress: Option<Arc<ProgressBus>>,
    /// Optional `Space`-key pause gate: the sweep waits on it before
    /// spawning each ladder level (in-flight streams complete).
    pause: Option<Arc<RunPause>>,
    /// Optional run logger: the sweep records step starts / completions,
    /// per-worker timeouts, stalls, and step aborts.
    logger: Option<Arc<RunLogger>>,
    /// The inter-token stall-detection window (no tokens for this long →
    /// warn). The TTFB phase (no token yet) uses the longer
    /// [`DEFAULT_TTFB_STALL_TIMEOUT`] / `worker_timeout` / 2 threshold.
    stall_timeout: Duration,
    /// Optional hard cap on the computed step budget (tests use it to
    /// make a hanging level abort quickly; production leaves it `None`).
    step_budget_override: Option<Duration>,
}

impl std::fmt::Debug for Sweep {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Sweep")
            .field("pool", &self.pool)
            .field("ladder", &self.ladder)
            .field("metrics", &self.metrics.is_some())
            .field("progress", &self.progress.is_some())
            .field("pause", &self.pause.is_some())
            .field("logger", &self.logger.is_some())
            .field("stall_timeout", &self.stall_timeout)
            .field("step_budget_override", &self.step_budget_override)
            .finish()
    }
}

impl Sweep {
    /// Create a sweep over `ladder` (normalized: positive, deduped,
    /// ascending). Use [`DEFAULT_LADDER`] for the blueprint default.
    pub fn new(pool: WorkerPool, ladder: impl IntoIterator<Item = usize>) -> Self {
        Self {
            pool,
            ladder: normalize_ladder(ladder),
            metrics: None,
            progress: None,
            pause: None,
            logger: None,
            stall_timeout: DEFAULT_STALL_TIMEOUT,
            step_budget_override: None,
        }
    }

    /// The (normalized) ladder this sweep steps through.
    pub fn ladder(&self) -> &[usize] {
        &self.ladder
    }

    /// Publish live snapshots to a shared [`MetricsState`] while the sweep
    /// runs (plan: the sweep coordinates the TUI's stream matrix / gauges
    /// via the Chunk 6 double buffer).
    pub fn metrics(mut self, state: Arc<MetricsState>) -> Self {
        self.metrics = Some(state);
        self
    }

    /// Attach a [`ProgressBus`] so the sweep reports its ladder position
    /// (`level`, `step`, streams active) to the Benchmark Sequence.
    pub fn progress(mut self, bus: Arc<ProgressBus>) -> Self {
        self.progress = Some(bus);
        self
    }

    /// Attach the `Space`-key pause gate: each ladder level waits on it
    /// before its `n` workers are spawned (the headless path leaves it
    /// `None`).
    pub fn pause(mut self, gate: Arc<RunPause>) -> Self {
        self.pause = Some(gate);
        self
    }

    /// Attach the run logger: the sweep then records its per-step
    /// lifecycle (start, worker timeouts, stalls, step aborts, summary)
    /// to the file-based log.
    pub fn logger(mut self, logger: Arc<RunLogger>) -> Self {
        self.logger = Some(logger);
        self
    }

    /// Override the inter-token stall-detection window (default
    /// [`DEFAULT_STALL_TIMEOUT`]). The TTFB phase (no token received
    /// yet) always uses the longer [`DEFAULT_TTFB_STALL_TIMEOUT`] (or the
    /// pool's per-worker timeout / 2, when that is larger).
    pub fn stall_timeout(mut self, d: Duration) -> Self {
        self.stall_timeout = d;
        self
    }

    /// Cap the computed step budget from above (a test hook: a hanging
    /// level can then be made to abort in seconds instead of minutes).
    pub fn step_budget(mut self, d: Duration) -> Self {
        self.step_budget_override = Some(d);
        self
    }

    fn logi(&self, ctx: Context, msg: String) {
        if let Some(l) = &self.logger {
            l.info(ctx, msg);
        }
    }

    fn logw(&self, ctx: Context, msg: String) {
        if let Some(l) = &self.logger {
            l.warn(ctx, msg);
        }
    }

    fn loge(&self, ctx: Context, msg: String) {
        if let Some(l) = &self.logger {
            l.error(ctx, msg);
        }
    }

    /// Run the full sweep: one level at a time, in ladder order.
    ///
    /// **The freeze fix:** each level is bounded three ways —
    ///
    /// 1. **per-worker timeout** (the pool's `worker_timeout`): a worker
    ///    that does not finish in time is killed and reported as a
    ///    `WorkerTimeout` failure with its partial tokens;
    /// 2. **stall detection**: a worker that received tokens and then
    ///    goes silent for [`DEFAULT_STALL_TIMEOUT`] is warned as
    ///    stalled; a worker still in the TTFB phase (no token yet) is
    ///    warned only after the longer
    ///    [`DEFAULT_TTFB_STALL_TIMEOUT`] / `worker_timeout` / 2 leash —
    ///    high-concurrency server queuing is not a stall (it
    ///    distinguishes a slow server from a hung connection — the
    ///    kill comes from #1);
    /// 3. **step-level timeout**: if the whole level runs past its budget
    ///    (3× the previous step, floored at the worker cap), it is
    ///    warned, and at 2× the budget the level is *aborted* — partial
    ///    results are collected, the level is marked `degraded`, and the
    ///    sweep continues to the next step. The sweep can never hang on
    ///    one bad level again.
    pub async fn run(&self) -> SweepResult {
        let mut levels = Vec::with_capacity(self.ladder.len());
        let mut prev_wall_ns = 0u64;
        self.logi(
            Context::EngineB,
            format!(
                "Engine B (Concurrency) started — ladder [{}]",
                self.ladder
                    .iter()
                    .map(|n| n.to_string())
                    .collect::<Vec<_>>()
                    .join(",")
            ),
        );
        for (i, &n) in self.ladder.iter().enumerate() {
            // The `Space`-key pause: hold before the next level's streams
            // go out (an in-flight level always completes).
            if let Some(gate) = &self.pause {
                gate.wait_while_paused().await;
            }
            let level = self
                .run_level(n, i + 1, self.ladder.len(), prev_wall_ns)
                .await;
            prev_wall_ns = level.wall_ns;
            levels.push(level);
        }
        self.logi(
            Context::EngineB,
            format!(
                "Engine B complete — {} level(s), {} degraded",
                levels.len(),
                levels.iter().filter(|l| l.degraded()).count()
            ),
        );
        SweepResult { levels }
    }

    /// The step-level budget: `max(worker cap, 3× the previous step's
    /// wall time)` — a level that is 3× slower than the one before it is
    /// suspect (saturation / a hung level); with no worker cap set, the
    /// budget is `3× previous` (or a generous 5-minute floor on the first
    /// step).
    /// The effective step budget: the computed value
    /// (`max(worker cap, 3× previous step)`) capped by the optional
    /// [`step_budget`](Self::step_budget) override.
    pub fn effective_step_budget(&self, prev_wall_ns: u64) -> Duration {
        const NO_CAP_FLOOR: Duration = Duration::from_secs(300);
        let computed = match self.pool.worker_timeout_cap() {
            Some(cap) => {
                if prev_wall_ns > 0 {
                    cap.max(Duration::from_nanos(prev_wall_ns.saturating_mul(3)))
                } else {
                    cap
                }
            }
            None => {
                if prev_wall_ns > 0 {
                    Duration::from_nanos(prev_wall_ns.saturating_mul(3))
                } else {
                    NO_CAP_FLOOR
                }
            }
        };
        self.step_budget_override
            .map(|o| o.min(computed))
            .unwrap_or(computed)
    }

    /// Run one ladder level: spawn `n` workers, drain the aggregate channel
    /// into a [`LevelAccumulator`], and fold the level's metrics.
    ///
    /// The drain loop is a `tokio::select!` between the event channel and
    /// a 5 s watchdog tick (stall detection + step-budget enforcement), so
    /// a level always ends: either every worker terminates (the channel
    /// closes) or the step timeout aborts it.
    async fn run_level(
        &self,
        n: usize,
        step: usize,
        total_steps: usize,
        prev_wall_ns: u64,
    ) -> SweepLevel {
        let start = MonotonicInstant::now();
        self.logi(
            Context::EngineB,
            format!("Step {step}/{total_steps}: concurrency={n}, spawning {n} worker(s)"),
        );
        if let Some(bus) = &self.progress {
            bus.publish(EngineProgress::Concurrency {
                level: n,
                step,
                total_steps,
                active: 0,
            });
        }
        let (mut rx, supervisor) = self.pool.clone().spawn_tagged(n, &format!("B{step}"));
        let mut acc = LevelAccumulator::new(n, self.pool.max_tokens());
        let budget = self.effective_step_budget(prev_wall_ns);
        let mut stall_tick = tokio::time::interval(STALL_CHECK_INTERVAL);
        stall_tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
        let mut step_warned = false;
        let mut aborted = false;
        let mut batch = 0u32;
        loop {
            tokio::select! {
                event = rx.recv() => {
                    match event {
                        Some(e) => {
                            acc.on_event(&e);
                            self.log_pool_event(&e, &acc, step, total_steps);
                            batch += 1;
                            if let Some(state) = &self.metrics {
                                // Batched publish (blueprint §4.2: the
                                // engine "pushes unified snapshots per
                                // batch") — every 16 events, plus a final
                                // one when the level finishes.
                                if batch >= 16 {
                                    state.update(self.live_snapshot(&acc, n, &start, StreamStatus::Streaming));
                                    batch = 0;
                                }
                            }
                            // The progress bus shares the batch cadence:
                            // the live stream count is the "alive" signal
                            // while a level runs.
                            if let Some(bus) = &self.progress {
                                if batch >= 16 {
                                    bus.publish(EngineProgress::Concurrency {
                                        level: n,
                                        step,
                                        total_steps,
                                        active: acc.active(),
                                    });
                                }
                            }
                        }
                        // Channel closed ⇒ every worker has ended (or was
                        // killed); the level is done.
                        None => break,
                    }
                }
                _ = stall_tick.tick() => {
                    self.check_stalls(&mut acc, step, total_steps, &start);
                    let elapsed = start.elapsed();
                    if elapsed > budget {
                        if !step_warned {
                            step_warned = true;
                            self.logw(
                                Context::EngineB,
                                format!(
                                    "Step {step}/{total_steps}: running {:.1}s — past the {:.0}s budget (3× previous step / worker cap); workers still alive",
                                    elapsed.as_secs_f64(),
                                    budget.as_secs_f64()
                                ),
                            );
                        }
                        if elapsed > budget * 2 {
                            self.loge(
                                Context::EngineB,
                                format!(
                                    "Step {step}/{total_steps}: STEP TIMEOUT after {:.1}s (2× the {:.0}s budget) — aborting level, collecting partial results",
                                    elapsed.as_secs_f64(),
                                    budget.as_secs_f64()
                                ),
                            );
                            // Kill the supervisor task: it owns the worker
                            // tasks (its spawned children), so they are
                            // aborted with it; their sockets close.
                            supervisor.abort();
                            aborted = true;
                            break;
                        }
                    }
                }
            }
        }
        // On the normal path the supervisor resolves at the true end of
        // the level; after an `abort()` it returns a `JoinError`
        // immediately.
        let _outcomes: Option<Vec<crate::client::StreamOutcome>> = supervisor.await.ok();
        let wall_ns = start.delta_nanos(&MonotonicInstant::now());
        // Any worker still in flight (only possible after an abort) is
        // marked as a failed stream so the level's counts add up.
        acc.finalize_incomplete(aborted);
        if let Some(state) = &self.metrics {
            let status = if acc.failed() == n {
                StreamStatus::Error
            } else {
                StreamStatus::Done
            };
            state.update(self.live_snapshot(&acc, n, &start, status));
        }
        if let Some(bus) = &self.progress {
            bus.publish(EngineProgress::Concurrency {
                level: n,
                step,
                total_steps,
                active: acc.active(),
            });
        }
        let level = acc.finish(wall_ns, aborted);
        self.logi(
            Context::EngineB,
            format!(
                "Step {step}/{total_steps}: aggregate={:.1} t/s, p50={:.1}ms, p99={:.1}ms, {} completed, {} failed, {} timed out, {:.1}s{}",
                level.aggregate_tps,
                level.p50_tpot_ms(),
                level.p99_tpot_ms(),
                level.completed_streams,
                level.failed_streams,
                level.timed_out_streams,
                level.wall_secs(),
                if level.degraded() { " [DEGRADED]" } else { "" }
            ),
        );
        level
    }

    /// Stall detection: warn (once per worker) when a live worker has
    /// been silent past its *phase-appropriate* threshold:
    ///
    /// * **TTFB phase** (no token received yet): the worker is likely
    ///   queued at the server (batch-scheduling delay at high
    ///   concurrency), not stalled — it gets the longer
    ///   [`ttfb_stall_threshold`](Self::ttfb_stall_threshold) leash;
    /// * **inter-token phase** (at least one token received, then
    ///   silence): [`stall_timeout`](Self::stall_timeout) (default
    ///   30 s) — this *is* a real stall.
    ///
    /// A warning only — the kill comes from the per-worker timeout, so a
    /// *slow* server (tokens every 40 s) is distinguished from a *hung*
    /// connection (no tokens, ever) in the log.
    fn check_stalls(
        &self,
        acc: &mut LevelAccumulator,
        step: usize,
        total_steps: usize,
        start: &MonotonicInstant,
    ) {
        if self.logger.is_none() {
            return; // no observer → no work
        }
        let now = MonotonicInstant::now();
        for t in &mut acc.trackers {
            if t.finished {
                continue;
            }
            let ref_t = t.last_token_at.unwrap_or(*start);
            let idle_ns = ref_t.delta_nanos(&now);
            let threshold = if t.last_token_at.is_none() {
                self.ttfb_stall_threshold()
            } else {
                self.stall_timeout
            };
            if (idle_ns as u128) >= threshold.as_nanos() && !t.stall_warned {
                t.stall_warned = true;
                if t.last_token_at.is_none() {
                    // TTFB phase: no token yet — the server is queuing
                    // this level's concurrent requests (normal at high
                    // concurrency), not stalled.
                    self.logw(
                        Context::EngineB,
                        format!(
                            "Step {step}/{total_steps}: worker #{} awaiting first token (TTFB: {:.0}s) — server queuing {} concurrent requests",
                            t.id,
                            idle_ns as f64 / 1e9,
                            acc.n
                        ),
                    );
                } else {
                    // Inter-token phase: at least one token arrived, then
                    // silence — a real stall.
                    let last = t
                        .last_token_wall
                        .map(|w| {
                            let ms = w
                                .duration_since(UNIX_EPOCH)
                                .map(|d| d.as_millis() as u64)
                                .unwrap_or(0);
                            crate::log::format_timestamp(ms, false)
                        })
                        .unwrap_or_else(|| "unknown".to_string());
                    self.logw(
                        Context::EngineB,
                        format!(
                            "Step {step}/{total_steps}: worker #{} stalled: no tokens for {:.0}s (last token at {last})",
                            t.id,
                            idle_ns as f64 / 1e9
                        ),
                    );
                }
            }
        }
    }

    /// The TTFB-phase stall threshold: the pool's per-worker timeout / 2
    /// when one is set (the kill is the full cap, so half of it is a
    /// reasonable "queued, not hung" warning point), floored at
    /// [`DEFAULT_TTFB_STALL_TIMEOUT`] (90 s).
    fn ttfb_stall_threshold(&self) -> Duration {
        self.pool
            .worker_timeout_cap()
            .map(|cap| (cap / 2).max(DEFAULT_TTFB_STALL_TIMEOUT))
            .unwrap_or(DEFAULT_TTFB_STALL_TIMEOUT)
    }

    /// Log the per-worker terminal events (stream complete / failure).
    /// Token-reception milestones (first token, every 50th) are logged by
    /// the workers themselves (the `B{step}-{id}` tags).
    fn log_pool_event(
        &self,
        e: &PoolEvent,
        acc: &LevelAccumulator,
        step: usize,
        total_steps: usize,
    ) {
        match e {
            PoolEvent::Complete { stream, .. } => {
                let tokens = acc
                    .trackers
                    .get(*stream as usize)
                    .map(|t| t.tokens())
                    .unwrap_or(0);
                self.logi(
                    Context::Sse,
                    format!("B{step}-{stream} stream complete: {tokens} tokens"),
                );
            }
            PoolEvent::Failed { stream, error, .. } => {
                let tokens = acc
                    .trackers
                    .get(*stream as usize)
                    .map(|t| t.tokens())
                    .unwrap_or(0);
                match error {
                    StreamError::WorkerTimeout(d) => self.logw(
                        Context::EngineB,
                        format!(
                            "Step {step}/{total_steps}: worker #{stream} TIMEOUT after {d:?} — collected {tokens} tokens (killed)",
                        ),
                    ),
                    StreamError::Timeout(d) => self.logw(
                        Context::EngineB,
                        format!(
                            "Step {step}/{total_steps}: worker #{stream} stalled — no data for {d:?} (killed)",
                        ),
                    ),
                    other => self.loge(
                        Context::EngineB,
                        format!(
                            "Step {step}/{total_steps}: worker #{stream} failed: {other} (collected {tokens} tokens)",
                        ),
                    ),
                }
            }
            PoolEvent::Frame { .. } => {}
        }
    }

    /// The live (in-level) snapshot published to the TUI seam.
    fn live_snapshot(
        &self,
        acc: &LevelAccumulator,
        n: usize,
        start: &MonotonicInstant,
        status: StreamStatus,
    ) -> MetricsSnapshot {
        let elapsed_ns = start.delta_nanos(&MonotonicInstant::now()).max(1);
        let tokens = acc.tokens_so_far();
        let snapshot = MetricsSnapshot {
            endpoint: self.pool.endpoint().to_string(),
            model: self.pool.model().to_string(),
            mode: "Concurrency".to_string(),
            aggregate_tps: tokens as f64 / (elapsed_ns as f64 / 1_000_000_000.0),
            // Server-reported prompt totals (usage frames): the metrics
            // seam derives `prompt_throughput` = prompt / mean TTFT from
            // this plus the per-stream TTFTs.
            prompt_tokens: acc.prompt_tokens_so_far(),
            active_streams: acc.active(),
            total_streams: n,
            status,
            streams: acc.stream_rows(),
            ..Default::default()
        };
        snapshot.with_itl_percentiles(acc.itl())
    }
}

/// Per-stream state folded from the aggregate channel while a level runs.
struct StreamTracker {
    id: u32,
    state: StreamStatus,
    reasoning_frames: u64,
    content_frames: u64,
    /// All data frames received (MTP packet denominator, blueprint §7).
    packets: u64,
    last_token_at: Option<MonotonicInstant>,
    /// Wall-clock time of the last token (the stall log's "last token at
    /// HH:MM:SS" — a display concern, never on the quanta timing path).
    last_token_wall: Option<SystemTime>,
    ttft_ns: Option<u64>,
    t3: Option<MonotonicInstant>,
    t_end: Option<MonotonicInstant>,
    usage: Option<Usage>,
    premature: bool,
    error: Option<String>,
    finished: bool,
    /// The stall warning has fired for this worker (once per worker).
    stall_warned: bool,
    /// `true` when this worker was killed by the per-worker timeout.
    timed_out: bool,
}

impl StreamTracker {
    fn new(id: u32) -> Self {
        Self {
            id,
            state: StreamStatus::Waiting,
            reasoning_frames: 0,
            content_frames: 0,
            packets: 0,
            last_token_at: None,
            last_token_wall: None,
            ttft_ns: None,
            t3: None,
            t_end: None,
            usage: None,
            premature: false,
            error: None,
            finished: false,
            stall_warned: false,
            timed_out: false,
        }
    }

    /// Token frames seen (reasoning + content).
    fn token_frames(&self) -> u64 {
        self.reasoning_frames + self.content_frames
    }

    /// Tokens generated: server-reported `usage` when available, else the
    /// counted token frames (one token per frame is the worker's unit).
    fn tokens(&self) -> u64 {
        self.usage
            .map(|u| u.completion_tokens)
            .unwrap_or_else(|| self.token_frames())
    }

    /// The stream-matrix `TYPE` column: the dominant phase.
    fn kind(&self) -> String {
        if self.reasoning_frames > self.content_frames {
            "Reasoning".to_string()
        } else if self.content_frames > 0 {
            "Content".to_string()
        } else {
            "Control".to_string()
        }
    }

    fn row(&self, max_tokens: u32) -> StreamMetric {
        let tg = self.tokens();
        let ttft_s = self.ttft_ns.map(|ns| ns as f64 / 1_000_000_000.0);
        let gen_tps = match (self.t3, self.t_end) {
            (Some(t3), Some(end)) => {
                let span_s = t3.delta_nanos(&end) as f64 / 1_000_000_000.0;
                if span_s > 0.0 && tg > 0 {
                    Some(tg as f64 / span_s)
                } else {
                    None
                }
            }
            _ => None,
        };
        // MTP = output tokens / token-carrying packets (blueprint §7.4;
        // matches the Chunk 7 single-stream formula).
        let mtp = {
            let pk = self.token_frames();
            if pk > 0 {
                Some(tg as f64 / pk as f64)
            } else {
                None
            }
        };
        let progress = if self.finished {
            1.0
        } else if max_tokens > 0 {
            (tg as f64 / max_tokens as f64).min(1.0)
        } else {
            0.0
        };
        StreamMetric {
            id: self.id,
            kind: self.kind(),
            state: self.state,
            pp_tokens: self.usage.map(|u| u.prompt_tokens),
            tg_tokens: (tg > 0).then_some(tg),
            ttft_s,
            gen_tps,
            mtp,
            progress,
        }
    }
}

/// The per-level fold: pooled ITL / TTFT histograms plus one
/// [`StreamTracker`] per worker.
struct LevelAccumulator {
    n: usize,
    max_tokens: u32,
    /// Inter-token latencies pooled across all streams (TPOT).
    itl: LatencyHistogram,
    /// One TTFT sample per stream.
    ttft: LatencyHistogram,
    trackers: Vec<StreamTracker>,
}

impl LevelAccumulator {
    fn new(n: usize, max_tokens: u32) -> Self {
        Self {
            n,
            max_tokens,
            itl: LatencyHistogram::default(),
            ttft: LatencyHistogram::default(),
            trackers: (0..n).map(|i| StreamTracker::new(i as u32)).collect(),
        }
    }

    /// Fold one pooled event (the sweep's drain-loop hot path).
    ///
    /// The ITL sample is captured *before* taking the tracker's mutable
    /// borrow: `self.trackers` and `self.itl` are disjoint fields, so the
    /// sample (a plain `u64`) can be recorded while the tracker borrow is
    /// still live.
    fn on_event(&mut self, event: &PoolEvent) {
        match event {
            PoolEvent::Frame {
                frame,
                at,
                timestamps,
                stream,
            } => {
                let sample = self
                    .trackers
                    .get(*stream as usize)
                    .and_then(|t| t.last_token_at)
                    .map(|prev| prev.delta_nanos(at));
                let Some(t) = self.trackers.get_mut(*stream as usize) else {
                    return;
                };
                t.packets += 1;
                match &frame.chunk {
                    Chunk::Reasoning(_) => t.reasoning_frames += 1,
                    Chunk::Content(_) => t.content_frames += 1,
                    Chunk::Control | Chunk::Usage(_) => {}
                }
                if is_token_frame(&frame.chunk) {
                    if let Some(ns) = sample {
                        self.itl.record(ns);
                    }
                    t.last_token_at = Some(*at);
                    t.last_token_wall = Some(SystemTime::now());
                    if t.t3.is_none() {
                        t.t3 = Some(*at);
                    }
                    if t.state == StreamStatus::Waiting {
                        t.state = StreamStatus::Streaming;
                    }
                }
                if t.ttft_ns.is_none() {
                    t.ttft_ns = timestamps.ttft_nanos();
                }
            }
            PoolEvent::Complete {
                stream,
                timestamps,
                usage,
                premature,
                ..
            } => {
                let Some(t) = self.trackers.get_mut(*stream as usize) else {
                    return;
                };
                t.usage = *usage;
                t.premature = *premature;
                t.t_end = timestamps.t_end;
                if t.ttft_ns.is_none() {
                    t.ttft_ns = timestamps.ttft_nanos();
                }
                t.state = StreamStatus::Done;
                t.finished = true;
            }
            PoolEvent::Failed {
                stream,
                timestamps,
                error,
            } => {
                let Some(t) = self.trackers.get_mut(*stream as usize) else {
                    return;
                };
                t.t_end = timestamps.t_end;
                if t.ttft_ns.is_none() {
                    t.ttft_ns = timestamps.ttft_nanos();
                }
                t.timed_out = matches!(error, crate::client::StreamError::WorkerTimeout(_));
                t.error = Some(error.to_string());
                t.state = StreamStatus::Error;
                t.finished = true;
            }
        }
    }

    /// Token frames received so far (live-snapshot throughput numerator).
    fn tokens_so_far(&self) -> u64 {
        self.trackers.iter().map(|t| t.token_frames()).sum()
    }

    /// Prompt tokens reported by server `usage` so far (live-snapshot
    /// prompt-throughput numerator; the per-stream `pp_tokens` rows carry
    /// the same data for the UI's stream detail).
    fn prompt_tokens_so_far(&self) -> u64 {
        self.trackers
            .iter()
            .filter_map(|t| t.usage.map(|u| u.prompt_tokens))
            .sum()
    }

    /// Streams actively receiving tokens.
    fn active(&self) -> usize {
        self.trackers
            .iter()
            .filter(|t| t.state == StreamStatus::Streaming)
            .count()
    }

    /// Failed streams.
    fn failed(&self) -> usize {
        self.trackers
            .iter()
            .filter(|t| t.state == StreamStatus::Error)
            .count()
    }

    /// Per-stream detail rows (stream matrix / `stream_metrics`).
    fn stream_rows(&self) -> Vec<StreamMetric> {
        self.trackers
            .iter()
            .map(|t| t.row(self.max_tokens))
            .collect()
    }

    /// &self accessor for the ITL histogram (live-snapshot percentiles).
    fn itl(&self) -> &LatencyHistogram {
        &self.itl
    }

    /// Mark every worker that never reached a terminal event as failed.
    ///
    /// Only reachable after a step-level abort (on the normal channel-close
    /// path every worker has emitted exactly one terminal event, so there
    /// is nothing to finalize).
    fn finalize_incomplete(&mut self, aborted: bool) {
        for t in &mut self.trackers {
            if t.finished {
                continue;
            }
            t.finished = true;
            t.state = StreamStatus::Error;
            t.t_end = Some(MonotonicInstant::now());
            t.error = Some(if aborted {
                "aborted (step timeout)".to_string()
            } else {
                "incomplete (level ended)".to_string()
            });
        }
    }

    /// Fold the finished level into its [`SweepLevel`] curve point.
    fn finish(mut self, wall_ns: u64, aborted: bool) -> SweepLevel {
        let total_tokens: u64 = self.trackers.iter().map(|t| t.tokens()).sum();
        for t in &self.trackers {
            if let Some(ns) = t.ttft_ns {
                self.ttft.record(ns);
            }
        }
        let wall_ns = wall_ns.max(1);
        SweepLevel {
            concurrency: self.n,
            aggregate_tps: total_tokens as f64 / (wall_ns as f64 / 1_000_000_000.0),
            p50_tpot_ns: self.itl.p50() as u64,
            p90_tpot_ns: self.itl.p90() as u64,
            p99_tpot_ns: self.itl.p99() as u64,
            ttft_p50_ns: self.ttft.p50() as u64,
            ttft_p90_ns: self.ttft.p90() as u64,
            total_tokens,
            completed_streams: self
                .trackers
                .iter()
                .filter(|t| t.state == StreamStatus::Done)
                .count(),
            failed_streams: self.failed(),
            timed_out_streams: self.trackers.iter().filter(|t| t.timed_out).count(),
            aborted,
            wall_ns,
            streams: self.stream_rows(),
        }
    }
}

/// A frame carrying generated tokens (reasoning or content) — a `Usage` /
/// `Control` frame is not a token arrival (mirrors the Chunk 5 worker).
fn is_token_frame(chunk: &Chunk) -> bool {
    matches!(chunk, Chunk::Reasoning(_) | Chunk::Content(_))
}

/// Relative throughput change `prev → cur` (`(cur − prev) / prev`).
///
/// A non-positive baseline with a positive `cur` is treated as infinite
/// growth (never a plateau); a zero/zero pair is no change.
fn relative_gain(prev: f64, cur: f64) -> f64 {
    if prev <= 0.0 {
        return if cur > 0.0 { f64::INFINITY } else { 0.0 };
    }
    (cur - prev) / prev
}

/// Relative p90-TPOT change `prev → cur` (`cur / prev`).
///
/// A zero baseline with a positive `cur` is treated as an infinite spike;
/// a zero/zero pair is no change.
fn relative_spike(prev_ns: u64, cur_ns: u64) -> f64 {
    if prev_ns == 0 {
        return if cur_ns > 0 { f64::INFINITY } else { 0.0 };
    }
    cur_ns as f64 / prev_ns as f64
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sse::ParsedFrame;
    use crate::timing::StreamTimestamps;

    /// Build a content frame event for `stream` at the mocked-clock instant.
    fn frame_event(stream: u32, ts: StreamTimestamps) -> PoolEvent {
        PoolEvent::Frame {
            stream,
            frame: ParsedFrame {
                chunk: Chunk::Content("tok".to_string()),
                t_nanos: 0,
                done: false,
            },
            at: MonotonicInstant::now(),
            timestamps: ts,
        }
    }

    /// A running timestamps record: `t0`/`t1` at `t1`, `t2`/`t3` at `t3`.
    fn ts_with_ttft(t1: MonotonicInstant, t3: MonotonicInstant) -> StreamTimestamps {
        StreamTimestamps {
            t0: Some(t1),
            t1: Some(t1),
            t2: Some(t3),
            t3: Some(t3),
            t_end: None,
        }
    }

    /// Two streams, three content frames each arriving at 10/20/30 ms,
    /// completing at 30 ms; stream 0 TTFT 5 ms, stream 1 TTFT 15 ms.
    ///
    /// Built under a mocked quanta clock so every instant is exact — the
    /// deterministic fold assertions below depend on it.
    fn synthetic_events() -> Vec<PoolEvent> {
        let (clock, mock) = quanta::Clock::mock();
        quanta::with_clock(&clock, || {
            let t0 = MonotonicInstant::now(); // 0 ms
            mock.increment(5_000_000);
            let t3_0 = MonotonicInstant::now(); // 5 ms
            mock.increment(10_000_000);
            let t3_1 = MonotonicInstant::now(); // 15 ms
            mock.decrement(5_000_000);
            let at_1 = MonotonicInstant::now(); // 10 ms
            mock.increment(10_000_000);
            let at_2 = MonotonicInstant::now(); // 20 ms
            mock.increment(10_000_000);
            let at_3 = MonotonicInstant::now(); // 30 ms

            let mut events = Vec::new();
            for (stream, t3) in [(0u32, t3_0), (1u32, t3_1)] {
                for at in [at_1, at_2, at_3] {
                    let mut frame = frame_event(stream, ts_with_ttft(t0, t3));
                    // `frame_event` stamps `at` at the *current* mock time;
                    // overwrite with this frame's scheduled arrival.
                    match &mut frame {
                        PoolEvent::Frame { at: a, .. } => *a = at,
                        _ => unreachable!(),
                    }
                    events.push(frame);
                }
                events.push(PoolEvent::Complete {
                    stream,
                    timestamps: StreamTimestamps {
                        t0: Some(t0),
                        t1: Some(t0),
                        t2: Some(t3),
                        t3: Some(t3),
                        t_end: Some(at_3),
                    },
                    usage: Some(Usage {
                        prompt_tokens: 10,
                        completion_tokens: 3,
                    }),
                    premature: false,
                    malformed_frames: 0,
                });
            }
            events
        })
    }

    #[test]
    fn default_ladder_matches_blueprint() {
        assert_eq!(DEFAULT_LADDER, [1, 2, 4, 8, 16, 32, 64]);
    }

    #[test]
    fn normalize_ladder_drops_zero_dedups_and_sorts() {
        assert_eq!(normalize_ladder([4, 0, 2, 4, 1, 8]), [1, 2, 4, 8]);
        assert_eq!(normalize_ladder([]), Vec::<usize>::new());
        assert_eq!(normalize_ladder([0, 0]), Vec::<usize>::new());
    }

    #[test]
    fn fold_level_computes_aggregate_tps_and_pooled_p90_tpot() {
        let events = synthetic_events();
        let mut acc = LevelAccumulator::new(2, 16);
        for e in &events {
            acc.on_event(e);
        }
        // 30 ms wall time.
        let level = acc.finish(30_000_000, false);
        assert_eq!(level.concurrency, 2);
        // usage (3 + 3) is the token source of truth.
        assert_eq!(level.total_tokens, 6);
        // 6 tokens / 0.03 s.
        assert!((level.aggregate_tps - 200.0).abs() < 0.01);
        // Every ITL sample is exactly 10 ms (4 samples, 2 streams); the
        // histogram reports it within its 3-significant-digit bucket
        // (10.0–10.1 ms).
        for v in [level.p50_tpot_ns, level.p90_tpot_ns, level.p99_tpot_ns] {
            assert!(
                (10_000_000..10_100_000).contains(&v),
                "ITL sample out of 10 ms bucket: {v}"
            );
        }
        assert_eq!(level.completed_streams, 2);
        assert_eq!(level.failed_streams, 0);
        assert_eq!(level.wall_ns, 30_000_000);
    }

    #[test]
    fn fold_level_records_ttft_and_per_stream_detail() {
        let events = synthetic_events();
        let mut acc = LevelAccumulator::new(2, 16);
        for e in &events {
            acc.on_event(e);
        }
        let level = acc.finish(30_000_000, false);
        // TTFTs: stream 0 → 5 ms (t3 - t1 from its first frame's
        // timestamps), stream 1 → 15 ms — each inside its histogram bucket.
        assert!(
            (5_000_000..5_010_000).contains(&level.ttft_p50_ns),
            "ttft p50: {}",
            level.ttft_p50_ns
        );
        assert!(
            (15_000_000..15_010_000).contains(&level.ttft_p90_ns),
            "ttft p90: {}",
            level.ttft_p90_ns
        );

        let s0 = &level.streams[0];
        let s1 = &level.streams[1];
        assert_eq!(s0.id, 0);
        assert_eq!(s1.id, 1);
        assert_eq!(s0.state, StreamStatus::Done);
        assert_eq!(s1.state, StreamStatus::Done);
        assert_eq!(s0.kind, "Content");
        assert_eq!(s0.pp_tokens, Some(10));
        assert_eq!(s0.tg_tokens, Some(3));
        assert!((s0.ttft_s.unwrap() - 0.005).abs() < 1e-9);
        assert!((s1.ttft_s.unwrap() - 0.015).abs() < 1e-9);
        // MTP = 3 tokens / 3 token frames = 1.0 (standard auto-regressive).
        assert!((s0.mtp.unwrap() - 1.0).abs() < 1e-9);
        // Generation speed = 3 tokens over the t3→t_end span.
        assert!(s0.gen_tps.is_some());
        assert!(s1.gen_tps.is_some());
        assert_eq!(s0.progress, 1.0);
    }

    #[test]
    fn fold_level_counts_failed_streams() {
        let (clock, mock) = quanta::Clock::mock();
        quanta::with_clock(&clock, || {
            let t0 = MonotonicInstant::now();
            let mut acc = LevelAccumulator::new(2, 16);
            // Stream 0 delivers one token, then fails.
            acc.on_event(&frame_event(0, ts_with_ttft(t0, t0)));
            mock.increment(5_000_000);
            let t1 = MonotonicInstant::now();
            acc.on_event(&PoolEvent::Failed {
                stream: 0,
                timestamps: StreamTimestamps {
                    t0: Some(t0),
                    t1: Some(t0),
                    t2: Some(t1),
                    t3: Some(t1),
                    t_end: Some(t1),
                },
                error: crate::client::StreamError::Connection("refused".to_string()),
            });
            // Stream 1 completes cleanly with no frames.
            acc.on_event(&PoolEvent::Complete {
                stream: 1,
                timestamps: StreamTimestamps {
                    t0: Some(t0),
                    t1: Some(t0),
                    t2: Some(t1),
                    t3: None,
                    t_end: Some(t1),
                },
                usage: None,
                premature: false,
                malformed_frames: 0,
            });
            let level = acc.finish(5_000_000, false);
            assert_eq!(level.failed_streams, 1);
            assert_eq!(level.completed_streams, 1);
            assert_eq!(level.streams[0].state, StreamStatus::Error);
            assert_eq!(level.streams[1].state, StreamStatus::Done);
            // Failed stream's partial token still counts toward the total
            // (no usage → counted frames).
            assert_eq!(level.total_tokens, 1);
        });
    }

    #[test]
    fn fold_level_premature_completion_preserves_partial_data() {
        let (clock, mock) = quanta::Clock::mock();
        quanta::with_clock(&clock, || {
            let t0 = MonotonicInstant::now();
            let mut acc = LevelAccumulator::new(1, 16);
            acc.on_event(&frame_event(0, ts_with_ttft(t0, t0)));
            mock.increment(10_000_000);
            let t1 = MonotonicInstant::now();
            acc.on_event(&PoolEvent::Complete {
                stream: 0,
                timestamps: StreamTimestamps {
                    t0: Some(t0),
                    t1: Some(t0),
                    t2: Some(t1),
                    t3: Some(t1),
                    t_end: Some(t1),
                },
                usage: None,
                premature: true,
                malformed_frames: 0,
            });
            let level = acc.finish(10_000_000, false);
            // Premature is a completion, not a failure (Chunk 5 contract:
            // partial data is preserved).
            assert_eq!(level.completed_streams, 1);
            assert_eq!(level.failed_streams, 0);
            assert_eq!(level.total_tokens, 1);
            assert!(level.streams[0].tg_tokens == Some(1));
        });
    }

    #[test]
    fn empty_level_yields_zeroed_point() {
        let acc = LevelAccumulator::new(0, 16);
        let level = acc.finish(1_000_000, false);
        assert_eq!(level.concurrency, 0);
        assert_eq!(level.total_tokens, 0);
        assert_eq!(level.aggregate_tps, 0.0);
        assert!(level.streams.is_empty());
    }

    #[test]
    fn peak_throughput_picks_the_max() {
        let mk = |c: usize, tps: f64| SweepLevel {
            concurrency: c,
            aggregate_tps: tps,
            p50_tpot_ns: 0,
            p90_tpot_ns: 0,
            p99_tpot_ns: 0,
            ttft_p50_ns: 0,
            ttft_p90_ns: 0,
            total_tokens: 0,
            completed_streams: 0,
            failed_streams: 0,
            timed_out_streams: 0,
            aborted: false,
            wall_ns: 0,
            streams: Vec::new(),
        };
        let result = SweepResult {
            levels: vec![mk(1, 100.0), mk(2, 350.0), mk(4, 340.0), mk(8, 200.0)],
        };
        assert_eq!(result.peak_throughput().unwrap().concurrency, 2);
        assert!(SweepResult::default().is_empty());
    }

    /// A minimal curve point for knee-detection tests (only the fields the
    /// detector reads are set; the rest are zeroed/placeholder).
    fn level(concurrency: usize, tps: f64, p90_ms: f64) -> SweepLevel {
        SweepLevel {
            concurrency,
            aggregate_tps: tps,
            p50_tpot_ns: (p90_ms * 0.8e6) as u64,
            p90_tpot_ns: (p90_ms * 1e6) as u64,
            p99_tpot_ns: (p90_ms * 2e6) as u64,
            ttft_p50_ns: 10_000_000,
            ttft_p90_ns: 20_000_000,
            total_tokens: 100,
            completed_streams: concurrency,
            failed_streams: 0,
            timed_out_streams: 0,
            aborted: false,
            wall_ns: 1_000_000_000,
            streams: Vec::new(),
        }
    }

    #[test]
    fn detect_knee_finds_the_injected_inflection() {
        // Throughput climbs 100→340, plateaus at 16 (+1.5%, ≤ 5%), then
        // decays. p90 TPOT stays sub-2× until 16, where it spikes 3×
        // (10→30 ms) and keeps climbing — a clear saturation knee at 16.
        let result = SweepResult {
            levels: vec![
                level(1, 100.0, 5.0),
                level(2, 190.0, 6.0),
                level(4, 280.0, 7.0),
                level(8, 340.0, 10.0),
                level(16, 345.0, 30.0),
                level(32, 342.0, 60.0),
                level(64, 338.0, 90.0),
            ],
        };
        let knee = result.detect_knee().expect("knee detected");
        assert_eq!(knee.concurrency, 16, "knee at the injected inflection");
        assert_eq!(knee.sweet_spot, 8, "sweet spot is the last healthy level");
        assert!((knee.aggregate_tps - 345.0).abs() < 1e-9);
        assert_eq!(knee.p90_tpot_ns, 30_000_000);
    }

    #[test]
    fn detect_knee_none_when_the_curve_is_healthy() {
        // Throughput keeps growing (every gain > 5%) and p90 TPOT never
        // doubles — no saturation transition, so no knee.
        let result = SweepResult {
            levels: vec![
                level(1, 100.0, 5.0),
                level(2, 180.0, 5.0),
                level(4, 300.0, 6.0),
                level(8, 420.0, 6.0),
            ],
        };
        assert!(result.detect_knee().is_none());
    }

    #[test]
    fn detect_knee_none_with_fewer_than_two_levels() {
        assert!(SweepResult::default().detect_knee().is_none());
        let single = SweepResult {
            levels: vec![level(1, 100.0, 5.0)],
        };
        assert!(single.detect_knee().is_none());
    }

    #[test]
    fn detect_knee_degrading_throughput_knees_at_first_spike() {
        // Throughput decays monotonically (every gain is negative, hence ≤
        // the threshold); the knee is the first level where p90 spikes 2×
        // (6→12 ms).
        let result = SweepResult {
            levels: vec![
                level(1, 400.0, 5.0),
                level(2, 380.0, 6.0),
                level(4, 350.0, 12.0),
                level(8, 300.0, 30.0),
            ],
        };
        let knee = result.detect_knee().expect("knee detected");
        assert_eq!(knee.concurrency, 4);
        assert_eq!(knee.sweet_spot, 2);
    }

    #[test]
    fn detect_knee_ignores_a_plateau_without_a_latency_spike() {
        // Throughput plateaus (even dips) at 4, but p90 TPOT never doubles
        // (7/6 ≈ 1.17×) — a plateau alone is not a saturation knee.
        let result = SweepResult {
            levels: vec![
                level(1, 100.0, 5.0),
                level(2, 350.0, 6.0),
                level(4, 300.0, 7.0),
            ],
        };
        assert!(result.detect_knee().is_none());
    }

    #[test]
    fn envelope_reports_knee_and_sweet_spot() {
        let result = SweepResult {
            levels: vec![
                level(1, 100.0, 5.0),
                level(2, 190.0, 6.0),
                level(4, 280.0, 7.0),
                level(8, 340.0, 10.0),
                level(16, 345.0, 30.0),
            ],
        };
        let env = result.envelope().expect("envelope");
        assert_eq!(env.sweet_spot, 8);
        assert!((env.aggregate_tps - 340.0).abs() < 1e-9);
        assert_eq!(env.p90_tpot_ns, 10_000_000);
        assert_eq!(env.knee.map(|k| k.concurrency), Some(16));
    }

    #[test]
    fn envelope_falls_back_to_peak_throughput_when_no_knee() {
        let result = SweepResult {
            levels: vec![
                level(1, 100.0, 5.0),
                level(2, 350.0, 6.0),
                level(4, 300.0, 7.0),
            ],
        };
        // No knee (plateau without a 2× latency spike) → the envelope is
        // the peak-throughput level (350 t/s @ 2).
        let env = result.envelope().expect("envelope");
        assert!(env.knee.is_none());
        assert_eq!(env.sweet_spot, 2);
        assert!((env.aggregate_tps - 350.0).abs() < 1e-9);
    }

    #[test]
    fn envelope_is_none_for_an_empty_curve() {
        assert!(SweepResult::default().envelope().is_none());
    }

    #[test]
    fn relative_gain_and_spike_handle_zero_baselines() {
        assert_eq!(relative_gain(0.0, 100.0), f64::INFINITY);
        assert_eq!(relative_gain(0.0, 0.0), 0.0);
        assert!((relative_gain(100.0, 150.0) - 0.5).abs() < 1e-9);
        assert_eq!(relative_spike(0, 10), f64::INFINITY);
        assert_eq!(relative_spike(0, 0), 0.0);
        assert!((relative_spike(10, 30) - 3.0).abs() < 1e-9);
    }

    #[tokio::test]
    async fn sweep_normalizes_its_ladder() {
        let pool = WorkerPool::new(reqwest::Client::new(), "http://127.0.0.1:1", "m", "p", 16);
        let sweep = Sweep::new(pool, vec![4, 0, 2, 4]);
        assert_eq!(sweep.ladder(), &[2, 4]);
    }

    #[tokio::test]
    async fn empty_ladder_yields_empty_result() {
        let pool = WorkerPool::new(reqwest::Client::new(), "http://127.0.0.1:1", "m", "p", 16);
        let sweep = Sweep::new(pool, Vec::<usize>::new());
        let result = sweep.run().await;
        assert!(result.is_empty());
    }

    // ── The freeze fix: step budget, finalize, timeouts, stalls ─────────

    fn pool_with_cap(cap: Option<u64>) -> WorkerPool {
        let mut pool = WorkerPool::new(reqwest::Client::new(), "http://127.0.0.1:1", "m", "p", 16);
        if let Some(s) = cap {
            pool = pool.worker_timeout(Duration::from_secs(s));
        }
        pool
    }

    #[test]
    fn step_budget_uses_the_worker_cap_as_a_floor() {
        let sweep = Sweep::new(pool_with_cap(Some(120)), [1]);
        // First step (no previous): the cap is the budget.
        assert_eq!(sweep.effective_step_budget(0), Duration::from_secs(120));
    }

    #[test]
    fn step_budget_scales_with_the_previous_step() {
        let sweep = Sweep::new(pool_with_cap(Some(120)), [1]);
        // Previous step ran 60 s → 3× (180 s) beats the 120 s cap.
        assert_eq!(
            sweep.effective_step_budget(60_000_000_000),
            Duration::from_secs(180)
        );
        // Previous step ran 10 s → the 120 s cap wins.
        assert_eq!(
            sweep.effective_step_budget(10_000_000_000),
            Duration::from_secs(120)
        );
    }

    #[test]
    fn step_budget_without_a_cap_uses_the_three_x_rule() {
        let sweep = Sweep::new(pool_with_cap(None), [1]);
        // No worker cap, no previous step: the 5-minute floor.
        assert_eq!(sweep.effective_step_budget(0), Duration::from_secs(300));
        // No worker cap, previous 100 s: 3×.
        assert_eq!(
            sweep.effective_step_budget(100_000_000_000),
            Duration::from_secs(300)
        );
    }

    #[test]
    fn step_budget_override_caps_the_computed_value() {
        let sweep =
            Sweep::new(pool_with_cap(Some(120)), [1]).step_budget(Duration::from_millis(1500));
        assert_eq!(sweep.effective_step_budget(0), Duration::from_millis(1500));
        assert_eq!(
            sweep.effective_step_budget(60_000_000_000),
            Duration::from_millis(1500)
        );
    }

    #[test]
    fn finalize_incomplete_marks_stranded_workers_as_failed() {
        let (clock, _mock) = quanta::Clock::mock();
        quanta::with_clock(&clock, || {
            let t0 = MonotonicInstant::now();
            let mut acc = LevelAccumulator::new(2, 16);
            // Stream 0 completes cleanly.
            acc.on_event(&frame_event(0, ts_with_ttft(t0, t0)));
            acc.on_event(&PoolEvent::Complete {
                stream: 0,
                timestamps: StreamTimestamps {
                    t0: Some(t0),
                    t1: Some(t0),
                    t2: Some(t0),
                    t3: Some(t0),
                    t_end: Some(t0),
                },
                usage: None,
                premature: false,
                malformed_frames: 0,
            });
            // Stream 1 never finished (the step was aborted).
            acc.finalize_incomplete(true);
            assert!(acc.trackers[0].finished);
            assert!(acc.trackers[1].finished);
            assert_eq!(acc.trackers[0].state, StreamStatus::Done);
            assert_eq!(acc.trackers[1].state, StreamStatus::Error);
            assert!(acc.trackers[1]
                .error
                .as_deref()
                .unwrap()
                .contains("aborted"));
            let level = acc.finish(1_000_000, true);
            assert!(level.aborted);
            assert!(level.degraded());
            assert_eq!(level.completed_streams, 1);
            assert_eq!(level.failed_streams, 1);
        });
    }

    #[test]
    fn fold_level_counts_worker_timeouts_and_flags_degraded() {
        let (clock, _mock) = quanta::Clock::mock();
        quanta::with_clock(&clock, || {
            let t0 = MonotonicInstant::now();
            let mut acc = LevelAccumulator::new(3, 16);
            // Stream 0: one token, then killed by the per-worker timeout.
            acc.on_event(&frame_event(0, ts_with_ttft(t0, t0)));
            acc.on_event(&PoolEvent::Failed {
                stream: 0,
                timestamps: StreamTimestamps {
                    t0: Some(t0),
                    t1: Some(t0),
                    t2: Some(t0),
                    t3: Some(t0),
                    t_end: Some(t0),
                },
                error: crate::client::StreamError::WorkerTimeout(Duration::from_secs(120)),
            });
            // Streams 1 and 2 complete cleanly.
            for s in [1u32, 2] {
                acc.on_event(&frame_event(s, ts_with_ttft(t0, t0)));
                acc.on_event(&PoolEvent::Complete {
                    stream: s,
                    timestamps: StreamTimestamps {
                        t0: Some(t0),
                        t1: Some(t0),
                        t2: Some(t0),
                        t3: Some(t0),
                        t_end: Some(t0),
                    },
                    usage: None,
                    premature: false,
                    malformed_frames: 0,
                });
            }
            let level = acc.finish(1_000_000, false);
            assert_eq!(level.timed_out_streams, 1);
            assert_eq!(level.completed_streams, 2);
            assert_eq!(level.failed_streams, 1);
            assert!(!level.aborted);
            assert!(level.degraded(), "a worker timeout degrades the level");
            // The timed-out stream's partial token still counts.
            assert_eq!(level.total_tokens, 3);
        });
    }

    #[test]
    fn clean_level_is_not_degraded() {
        let (clock, _mock) = quanta::Clock::mock();
        quanta::with_clock(&clock, || {
            let t0 = MonotonicInstant::now();
            let mut acc = LevelAccumulator::new(1, 16);
            acc.on_event(&frame_event(0, ts_with_ttft(t0, t0)));
            acc.on_event(&PoolEvent::Complete {
                stream: 0,
                timestamps: StreamTimestamps {
                    t0: Some(t0),
                    t1: Some(t0),
                    t2: Some(t0),
                    t3: Some(t0),
                    t_end: Some(t0),
                },
                usage: None,
                premature: false,
                malformed_frames: 0,
            });
            let level = acc.finish(1_000_000, false);
            assert!(!level.degraded());
        });
    }

    #[test]
    fn check_stalls_distinguishes_ttfb_from_inter_token() {
        let dir =
            std::env::temp_dir().join(format!("crucible-runlog-stall-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let logger = RunLogger::start(Some(&dir));
        // Pool cap 120 s → TTFB threshold = max(120/2, 90) = 90 s;
        // inter-token threshold = the 30 s default.
        let sweep = Sweep::new(pool_with_cap(Some(120)), [2]).logger(logger.clone());

        let (clock, mock) = quanta::Clock::mock();
        quanta::with_clock(&clock, || {
            let t0 = MonotonicInstant::now();
            let mut acc = LevelAccumulator::new(2, 16);
            // Stream 0 got its first token 6 s after the level start
            // (TTFB done → inter-token phase); stream 1 has had no
            // token since the level start (still in the TTFB phase —
            // queued at the server).
            let ts1 = ts_with_ttft(t0, t0);
            acc.on_event(&frame_event(0, ts1));
            {
                let t = &mut acc.trackers[0];
                mock.increment(6_000_000_000);
                t.last_token_at = Some(MonotonicInstant::now());
                t.last_token_wall = Some(std::time::SystemTime::now());
                t.state = StreamStatus::Streaming;
            }
            mock.increment(29_000_000_000); // now = t0 + 35 s

            // At 35 s: stream 0 is 29 s idle (< 30 s inter-token
            // threshold) and stream 1 is 35 s in TTFB (< 90 s TTFB
            // threshold) — neither warns (the old false positive).
            sweep.check_stalls(&mut acc, 1, 7, &t0);
            assert!(!acc.trackers[0].stall_warned);
            assert!(!acc.trackers[1].stall_warned);

            mock.increment(5_000_000_000); // now = t0 + 40 s
                                           // Stream 0 is now 34 s idle ≥ 30 s → inter-token stall.
                                           // Stream 1 is 40 s in TTFB < 90 s → still just queuing.
            sweep.check_stalls(&mut acc, 1, 7, &t0);
            assert!(acc.trackers[0].stall_warned);
            assert!(!acc.trackers[1].stall_warned);
            // The warning fires once (no repeat spam).
            sweep.check_stalls(&mut acc, 1, 7, &t0);
            assert!(acc.trackers[0].stall_warned);

            mock.increment(55_000_000_000); // now = t0 + 95 s
                                            // Stream 1 is now 95 s in TTFB ≥ 90 s → TTFB warning.
            sweep.check_stalls(&mut acc, 1, 7, &t0);
            assert!(acc.trackers[1].stall_warned);

            logger.finish();
            // The writer flushes on every newline; read after finish.
            let latest = std::fs::read_to_string(dir.join("latest.log")).unwrap();
            assert!(
                latest.contains("worker #0 stalled: no tokens for 34s"),
                "inter-token stall warning missing: {latest}"
            );
            assert!(
                latest.contains(
                    "worker #1 awaiting first token (TTFB: 95s) — server queuing 2 concurrent requests"
                ),
                "TTFB warning missing: {latest}"
            );
            // Each warning fires exactly once.
            assert_eq!(latest.matches("stalled: no tokens").count(), 1);
            assert_eq!(latest.matches("awaiting first token").count(), 1);
            let _ = std::fs::remove_dir_all(&dir);
        });
    }
}
